Hw1 task1
E1-Bart0/homework-repo pull request #1
Opened 2021-04-15 11:31 UTC by E1-Bart0

Homework1 Task1 Done

2021-04-17 09:49 UTC, Cjkjvfnby requested changes
I don't know if the tests check the correct values. 

Requirement for test: it is easy to check that values are correct only by looking at them.    

To achieve it use small numbers, use a short sequence.  The sequence of 5th and 6th elements behaves pretty same as 5000th and 5001st. 

So let's use only numbers from fib[:7] and sequence with size <=5 for testing.

2021-04-17 09:49 UTC, Cjkjvfnby commented on All_home_works/hw1/task1.py
> +    if not len(data):
Why do you need to check `len`?

2021-04-17 09:49 UTC, Cjkjvfnby commented on test/hw1/test_task1.py
> +    data = (
I'm pretty sure that you just copy-pasted these values from the output of your code.

Test that checks that one run of code ie equals another run of the same code only test that your output is stable. It has nothing with checking if the output is correct.

2021-04-18 10:43 UTC, Cjkjvfnby requested changes

2021-04-18 10:43 UTC, Cjkjvfnby commented on test/hw1/test_task1.py
> -def test_check_no_data():
Why did you remove this test?

2021-04-18 10:55 UTC, E1-Bart0 commented on test/hw1/test_task1.py
> -def test_check_no_data():
Because you asked why I am checking the length of data. So I thought it's unnecessary and removed the test.

2021-04-18 11:18 UTC, E1-Bart0 commented on test/hw1/test_task1.py
> -def test_check_no_data():
I see. "If len(data):" is the same way "if data:". Did you want this from me?

2021-04-18 22:21 UTC, Cjkjvfnby commented on test/hw1/test_task1.py
> -def test_check_no_data():
> "if data:"

Yes, that is what I want.

2021-04-22 19:11 UTC, Cjkjvfnby approved these changes

2021-04-23 05:57 UTC, merged