Hw6 task1
E1-Bart0/homework-repo pull request #23
Opened 2021-05-04 15:12 UTC by E1-Bart0

2021-05-04 17:30 UTC, Cjkjvfnby requested changes
You have implemented the task requirements. 

But let's try to find some corner cases when this does not work.

2021-05-05 10:41 UTC, E1-Bart0 commented
Are you talking about instances_counter or about class?
Are the cases when this does not work connected with class __new__ method?

2021-05-05 21:47 UTC, Cjkjvfnby commented
>  Are the cases when this does not work connected with class new method?

Kind of.     What else we could do with a class besides instancination?

2021-05-07 18:13 UTC, Cjkjvfnby requested changes

2021-05-07 18:13 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +def test__get_created_instances__check_method_from_class_instance(test_class):  # noqa:
`# noqa:` ?

2021-05-07 18:13 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +    _, _, _ = A(), A(), A()
Why do you need this line?

2021-05-07 18:13 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +def test__instances_counter_breaks_class_methods():
`breaks` -> `overwrites`  methods are not broken, they just replaced.

2021-05-07 18:13 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +    class B(type):
Actually, this is the same test as for an inheritance. 

Metaclass construct class before it is passed to our decorator.

2021-05-07 18:13 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +    class A(test_class):
Let's play with the initializer.  The different number of arguments, super and not super.  

Maybe some tests will require `pytest.raises`. We are documenting the behavior of the decorator.

2021-05-08 18:48 UTC, Cjkjvfnby approved these changes

2021-05-08 18:48 UTC, Cjkjvfnby commented on test/hw6/test_task1.py
> +        test_class.get_created_instances()
You can check that attribute is a string with less code.

2021-05-10 16:01 UTC, merged